### ISSUE TITLE
Database Service from Addons causes exceptions

### ISSUE THREAD

**Issue by MMasey** [UmbHost/UmbCheckout#85]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.2

### Bug summary

In my project I have recently added the Database Service from the Addons in order to update basket information in the database.

Since adding this, if I try to add a line item using BasketService.Add, or if I try to use DatabaseService.UpdateBasket, it get the following exception

### Specifics

```
[17:30:10 ERR] Unable to cast object of type 'System.Decimal' to type 'System.Nullable`1[System.Int64]'.
System.InvalidCastException: Unable to cast object of type 'System.Decimal' to type 'System.Nullable`1[System.Int64]'.
   at ..MoveNext()
--- End of stack trace from previous location ---
   at ..MoveNext()
[17:30:10 ERR] Unable to cast object of type 'System.Decimal' to type 'System.Nullable`1[System.Int64]'.
System.InvalidCastException: Unable to cast object of type 'System.Decimal' to type 'System.Nullable`1[System.Int64]'.
   at ..MoveNext()
--- End of stack trace from previous location ---
   at ..MoveNext()
--- End of stack trace from previous location ---
   at UmbCheckout.Core.Addons.NotificationHandlers.UpdateDatabaseNotificationHandler..MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Core.Events.INotificationAsyncHandler`1.HandleAsync(IEnumerable`1 notifications, CancellationToken cancellationToken)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCoreAsync[TNotification](IEnumerable`1 allHandlers, IEnumerable`1 notifications, CancellationToken cancellationToken)
   at Umbraco.Cms.Core.Events.NotificationAsyncHandlerWrapperImpl`1.HandleAsync[TNotification,TNotificationHandler](IEnumerable`1 notifications, CancellationToken cancellationToken, ServiceFactory serviceFactory, Func`4 publish)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotificationsAsync[TNotification,TNotificationHandler](IEnumerable`1 notifications, CancellationToken cancellationToken)
[17:30:10 ERR] One or more errors occurred. (One or more errors occurred. (Unable to cast object of type 'System.Decimal' to type 'System.Nullable`1[System.Int64]'.))
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Unable to cast object of type 'System.Decimal' to type 'System.Nullable`1[System.Int64]'.))
 ---> System.AggregateException: One or more errors occurred. (Unable to cast object of type 'System.Decimal' to type 'System.Nullable`1[System.Int64]'.)
 ---> System.InvalidCastException: Unable to cast object of type 'System.Decimal' to type 'System.Nullable`1[System.Int64]'.
   at ..MoveNext()
--- End of stack trace from previous location ---
   at ..MoveNext()
--- End of stack trace from previous location ---
   at UmbCheckout.Core.Addons.NotificationHandlers.UpdateDatabaseNotificationHandler..MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Core.Events.INotificationAsyncHandler`1.HandleAsync(IEnumerable`1 notifications, CancellationToken cancellationToken)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCoreAsync[TNotification](IEnumerable`1 allHandlers, IEnumerable`1 notifications, CancellationToken cancellationToken)
   at Umbraco.Cms.Core.Events.NotificationAsyncHandlerWrapperImpl`1.HandleAsync[TNotification,TNotificationHandler](IEnumerable`1 notifications, CancellationToken cancellationToken, ServiceFactory serviceFactory, Func`4 publish)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotificationsAsync[TNotification,TNotificationHandler](IEnumerable`1 notifications, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at Umbraco.Cms.Core.Events.EventAggregator.Publish[TNotification,TNotificationHandler](IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.ScopedNotificationPublisher`1.PublishScopedNotifications(IList`1 notifications)
   at Umbraco.Cms.Core.Events.ScopedNotificationPublisher`1.ScopeExit(Boolean completed)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.TryFinally(Action[] actions)
   --- End of inner exception stack trace ---
   at Umbraco.Cms.Infrastructure.Scoping.Scope.TryFinally(Action[] actions)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.Dispose()
   at UmbCheckout.Core.Services.BasketService.Add(LineItem item)
```

The above error seems to happen on the first attempt, although I am using the Database Service to Update the basket straight after adding a line item, and it almost looks likeit's not updating properly

I also get the following error when using the SessionService.UpdateBasket
```
[17:31:37 ERR] One or more errors occurred. (One or more errors occurred. (An item with the same key has already been added. Key: test))
System.AggregateException: One or more errors occurred. (One or more errors occurred. (An item with the same key has already been added. Key: test))
 ---> System.AggregateException: One or more errors occurred. (An item with the same key has already been added. Key: test)
 ---> System.ArgumentException: An item with the same key has already been added. Key: test
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at UmbCheckout.Core.Addons.NotificationHandlers.UpdateDatabaseNotificationHandler..MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Core.Events.INotificationAsyncHandler`1.HandleAsync(IEnumerable`1 notifications, CancellationToken cancellationToken)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCoreAsync[TNotification](IEnumerable`1 allHandlers, IEnumerable`1 notifications, CancellationToken cancellationToken)
   at Umbraco.Cms.Core.Events.NotificationAsyncHandlerWrapperImpl`1.HandleAsync[TNotification,TNotificationHandler](IEnumerable`1 notifications, CancellationToken cancellationToken, ServiceFactory serviceFactory, Func`4 publish)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotificationsAsync[TNotification,TNotificationHandler](IEnumerable`1 notifications, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at Umbraco.Cms.Core.Events.EventAggregator.Publish[TNotification,TNotificationHandler](IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.ScopedNotificationPublisher`1.PublishScopedNotifications(IList`1 notifications)
   at Umbraco.Cms.Core.Events.ScopedNotificationPublisher`1.ScopeExit(Boolean completed)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.TryFinally(Action[] actions)
   --- End of inner exception stack trace ---
   at Umbraco.Cms.Infrastructure.Scoping.Scope.TryFinally(Action[] actions)
   at Umbraco.Cms.Infrastructure.Scoping.Scope.Dispose()
   at UmbCheckout.Core.Services.SessionService.Update(Basket basket)
```

### Steps to reproduce

Set up a standard basket flow, then use the database service to update basket in the database, just after adding a line item, or using the session service to update the basket.

**Comment by AaronSadlerUK** [comment]
@MMasey Was this solved?

I think we worked through it

**Comment by MMasey** [comment]
Yeah, pretty sure it’s sorted. Will close it now 👍🏼
